//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf.Ui.Violeta.Gallery.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SH {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SH() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wpf.Ui.Violeta.Gallery.Resources.Localization.SH", typeof(SH).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpf.Ui.Violeta Gallery.
        /// </summary>
        internal static string Gallery_AppTitle {
            get {
                return ResourceManager.GetString("Gallery_AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse all controls by group.
        /// </summary>
        internal static string Gallery_Home_AllSamples_Desc {
            get {
                return ResourceManager.GetString("Gallery_Home_AllSamples_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button, SplitButton, LoadingButton, and more.
        /// </summary>
        internal static string Gallery_Home_Buttons_Desc {
            get {
                return ResourceManager.GetString("Gallery_Home_Buttons_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control categories.
        /// </summary>
        internal static string Gallery_Home_Categories {
            get {
                return ResourceManager.GetString("Gallery_Home_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataGrid, TreeListView, FlipView, Timeline.
        /// </summary>
        internal static string Gallery_Home_Collections_Desc {
            get {
                return ResourceManager.GetString("Gallery_Home_Collections_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComboBox, MultiComboBox, TreeComboBox.
        /// </summary>
        internal static string Gallery_Home_ComboBox_Desc {
            get {
                return ResourceManager.GetString("Gallery_Home_ComboBox_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typography, Icons, Colors.
        /// </summary>
        internal static string Gallery_Home_Design_Desc {
            get {
                return ResourceManager.GetString("Gallery_Home_Design_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContentDialog, MessageBox, Flyout.
        /// </summary>
        internal static string Gallery_Home_Dialogs_Desc {
            get {
                return ResourceManager.GetString("Gallery_Home_Dialogs_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RunningBlock, AsyncBox, Splash.
        /// </summary>
        internal static string Gallery_Home_Feedback_Desc {
            get {
                return ResourceManager.GetString("Gallery_Home_Feedback_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supports .NET Framework 4.6.2 through .NET 10, dark / light themes. Browse all samples by control type on the left..
        /// </summary>
        internal static string Gallery_Home_Hint {
            get {
                return ResourceManager.GetString("Gallery_Home_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoGrid, Form, Drawer, Divider.
        /// </summary>
        internal static string Gallery_Home_Layout_Desc {
            get {
                return ResourceManager.GetString("Gallery_Home_Layout_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImageView, PersonPicture, QrCode.
        /// </summary>
        internal static string Gallery_Home_Media_Desc {
            get {
                return ResourceManager.GetString("Gallery_Home_Media_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NavigationView, TabStrip, Anchor.
        /// </summary>
        internal static string Gallery_Home_Navigation_Desc {
            get {
                return ResourceManager.GetString("Gallery_Home_Navigation_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toast, Banner, TrayIcon.
        /// </summary>
        internal static string Gallery_Home_Notifications_Desc {
            get {
                return ResourceManager.GetString("Gallery_Home_Notifications_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumberBox, NumericUpDown, ButtonSpinner.
        /// </summary>
        internal static string Gallery_Home_NumberInput_Desc {
            get {
                return ResourceManager.GetString("Gallery_Home_NumberInput_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard.
        /// </summary>
        internal static string Gallery_Home_OpSystem_Desc {
            get {
                return ResourceManager.GetString("Gallery_Home_OpSystem_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DatePicker, ColorPicker, FilePicker.
        /// </summary>
        internal static string Gallery_Home_Pickers_Desc {
            get {
                return ResourceManager.GetString("Gallery_Home_Pickers_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckBox, RadioButton, ToggleSwitch, Rating.
        /// </summary>
        internal static string Gallery_Home_Selection_Desc {
            get {
                return ResourceManager.GetString("Gallery_Home_Selection_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme switching and about.
        /// </summary>
        internal static string Gallery_Home_Settings_Desc {
            get {
                return ResourceManager.GetString("Gallery_Home_Settings_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider, RangeSlider.
        /// </summary>
        internal static string Gallery_Home_Sliders_Desc {
            get {
                return ResourceManager.GetString("Gallery_Home_Sliders_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge, Skeleton, BusyMask.
        /// </summary>
        internal static string Gallery_Home_Status_Desc {
            get {
                return ResourceManager.GetString("Gallery_Home_Status_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An extended control library based on WPF-UI, providing Fluent Design advanced UI components..
        /// </summary>
        internal static string Gallery_Home_Subtitle {
            get {
                return ResourceManager.GetString("Gallery_Home_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label, TextBlock, Hyperlink.
        /// </summary>
        internal static string Gallery_Home_TextDisplay_Desc {
            get {
                return ResourceManager.GetString("Gallery_Home_TextDisplay_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextBox, PasswordBox, PinCode, TagInput.
        /// </summary>
        internal static string Gallery_Home_TextInput_Desc {
            get {
                return ResourceManager.GetString("Gallery_Home_TextInput_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShellWindow, TitleBar, Caption.
        /// </summary>
        internal static string Gallery_Home_Windows_Desc {
            get {
                return ResourceManager.GetString("Gallery_Home_Windows_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Gallery_Language {
            get {
                return ResourceManager.GetString("Gallery_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All samples.
        /// </summary>
        internal static string Gallery_Nav_AllSamples {
            get {
                return ResourceManager.GetString("Gallery_Nav_AllSamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buttons.
        /// </summary>
        internal static string Gallery_Nav_Buttons {
            get {
                return ResourceManager.GetString("Gallery_Nav_Buttons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collections.
        /// </summary>
        internal static string Gallery_Nav_Collections {
            get {
                return ResourceManager.GetString("Gallery_Nav_Collections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combo boxes.
        /// </summary>
        internal static string Gallery_Nav_ComboBox {
            get {
                return ResourceManager.GetString("Gallery_Nav_ComboBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design guidelines.
        /// </summary>
        internal static string Gallery_Nav_Design {
            get {
                return ResourceManager.GetString("Gallery_Nav_Design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialogs &amp; flyouts.
        /// </summary>
        internal static string Gallery_Nav_Dialogs {
            get {
                return ResourceManager.GetString("Gallery_Nav_Dialogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback &amp; animation.
        /// </summary>
        internal static string Gallery_Nav_Feedback {
            get {
                return ResourceManager.GetString("Gallery_Nav_Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Gallery_Nav_Home {
            get {
                return ResourceManager.GetString("Gallery_Nav_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        internal static string Gallery_Nav_Layout {
            get {
                return ResourceManager.GetString("Gallery_Nav_Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media.
        /// </summary>
        internal static string Gallery_Nav_Media {
            get {
                return ResourceManager.GetString("Gallery_Nav_Media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation.
        /// </summary>
        internal static string Gallery_Nav_Navigation {
            get {
                return ResourceManager.GetString("Gallery_Nav_Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications &amp; banners.
        /// </summary>
        internal static string Gallery_Nav_Notifications {
            get {
                return ResourceManager.GetString("Gallery_Nav_Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number input.
        /// </summary>
        internal static string Gallery_Nav_NumberInput {
            get {
                return ResourceManager.GetString("Gallery_Nav_NumberInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating system.
        /// </summary>
        internal static string Gallery_Nav_OpSystem {
            get {
                return ResourceManager.GetString("Gallery_Nav_OpSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pickers.
        /// </summary>
        internal static string Gallery_Nav_Pickers {
            get {
                return ResourceManager.GetString("Gallery_Nav_Pickers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection.
        /// </summary>
        internal static string Gallery_Nav_Selection {
            get {
                return ResourceManager.GetString("Gallery_Nav_Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sliders.
        /// </summary>
        internal static string Gallery_Nav_Sliders {
            get {
                return ResourceManager.GetString("Gallery_Nav_Sliders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status &amp; info.
        /// </summary>
        internal static string Gallery_Nav_Status {
            get {
                return ResourceManager.GetString("Gallery_Nav_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text display.
        /// </summary>
        internal static string Gallery_Nav_TextDisplay {
            get {
                return ResourceManager.GetString("Gallery_Nav_TextDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text input.
        /// </summary>
        internal static string Gallery_Nav_TextInput {
            get {
                return ResourceManager.GetString("Gallery_Nav_TextInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows &amp; shell.
        /// </summary>
        internal static string Gallery_Nav_Windows {
            get {
                return ResourceManager.GetString("Gallery_Nav_Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violeta Gallery.
        /// </summary>
        internal static string Gallery_PaneTitle {
            get {
                return ResourceManager.GetString("Gallery_PaneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        internal static string Gallery_SearchPlaceholder {
            get {
                return ResourceManager.GetString("Gallery_SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Gallery_Settings {
            get {
                return ResourceManager.GetString("Gallery_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string Gallery_Settings_About {
            get {
                return ResourceManager.GetString("Gallery_Settings_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpf.Ui.Violeta Gallery — a control demo and interaction verification app..
        /// </summary>
        internal static string Gallery_Settings_About_Desc {
            get {
                return ResourceManager.GetString("Gallery_Settings_About_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        internal static string Gallery_Settings_Appearance {
            get {
                return ResourceManager.GetString("Gallery_Settings_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch app theme and window backdrop. Theme can be changed quickly from the title bar; Backdrop depends on the OS version—unsupported options are disabled automatically..
        /// </summary>
        internal static string Gallery_Settings_Appearance_Desc {
            get {
                return ResourceManager.GetString("Gallery_Settings_Appearance_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window backdrop.
        /// </summary>
        internal static string Gallery_Settings_Backdrop {
            get {
                return ResourceManager.GetString("Gallery_Settings_Backdrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        internal static string Gallery_Settings_Backdrop_Auto {
            get {
                return ResourceManager.GetString("Gallery_Settings_Backdrop_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experimental (not fully adapted to WPF-UI yet).
        /// </summary>
        internal static string Gallery_Settings_Backdrop_Experimental {
            get {
                return ResourceManager.GetString("Gallery_Settings_Backdrop_Experimental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string Gallery_Settings_Backdrop_None {
            get {
                return ResourceManager.GetString("Gallery_Settings_Backdrop_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Gallery_Settings_Language {
            get {
                return ResourceManager.GetString("Gallery_Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch the gallery UI language. Changes apply immediately..
        /// </summary>
        internal static string Gallery_Settings_Language_Desc {
            get {
                return ResourceManager.GetString("Gallery_Settings_Language_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library version.
        /// </summary>
        internal static string Gallery_Settings_LibraryVersion {
            get {
                return ResourceManager.GetString("Gallery_Settings_LibraryVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NavigationView settings item.
        /// </summary>
        internal static string Gallery_Settings_NavItem {
            get {
                return ResourceManager.GetString("Gallery_Settings_NavItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page is opened via the NavigationView bottom settings button (IsSettingsVisible), demonstrating SettingsItem selection and page navigation..
        /// </summary>
        internal static string Gallery_Settings_NavItem_Desc {
            get {
                return ResourceManager.GetString("Gallery_Settings_NavItem_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime.
        /// </summary>
        internal static string Gallery_Settings_Runtime {
            get {
                return ResourceManager.GetString("Gallery_Settings_Runtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App settings.
        /// </summary>
        internal static string Gallery_Settings_Title {
            get {
                return ResourceManager.GetString("Gallery_Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string Gallery_Theme {
            get {
                return ResourceManager.GetString("Gallery_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string Gallery_Theme_Dark {
            get {
                return ResourceManager.GetString("Gallery_Theme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string Gallery_Theme_Light {
            get {
                return ResourceManager.GetString("Gallery_Theme_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string Gallery_Theme_System {
            get {
                return ResourceManager.GetString("Gallery_Theme_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app was minimized to the system tray. Double-click the icon to reopen..
        /// </summary>
        internal static string Gallery_Tray_MinimizedMessage {
            get {
                return ResourceManager.GetString("Gallery_Tray_MinimizedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string Gallery_Welcome {
            get {
                return ResourceManager.GetString("Gallery_Welcome", resourceCulture);
            }
        }
    }
}
