//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf.Ui.Violeta.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SH {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SH() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wpf.Ui.Violeta.Resources.Localization.SH", typeof(SH).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 复制.
        /// </summary>
        internal static string ButtonCopy {
            get {
                return ResourceManager.GetString("ButtonCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出.
        /// </summary>
        internal static string ButtonExit {
            get {
                return ResourceManager.GetString("ButtonExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 忽略.
        /// </summary>
        internal static string ButtonIgnore {
            get {
                return ResourceManager.GetString("ButtonIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 似乎遇到了一些问题.
        /// </summary>
        internal static string ExceptionWindowHint1 {
            get {
                return ResourceManager.GetString("ExceptionWindowHint1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您可以复制信息便于跟踪问题，尝试忽略问题或退出程序后重新启动。.
        /// </summary>
        internal static string ExceptionWindowHint2 {
            get {
                return ResourceManager.GetString("ExceptionWindowHint2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 出错啦.
        /// </summary>
        internal static string ExceptionWindowTitle {
            get {
                return ResourceManager.GetString("ExceptionWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误.
        /// </summary>
        internal static string MessageBoxCaptionError {
            get {
                return ResourceManager.GetString("MessageBoxCaptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示.
        /// </summary>
        internal static string MessageBoxCaptionInformation {
            get {
                return ResourceManager.GetString("MessageBoxCaptionInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 询问.
        /// </summary>
        internal static string MessageBoxCaptionQuestion {
            get {
                return ResourceManager.GetString("MessageBoxCaptionQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 警告.
        /// </summary>
        internal static string MessageBoxCaptionWarning {
            get {
                return ResourceManager.GetString("MessageBoxCaptionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 载入中.
        /// </summary>
        internal static string PendingBoxLoadingText {
            get {
                return ResourceManager.GetString("PendingBoxLoadingText", resourceCulture);
            }
        }
    }
}
