
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0019:Use pattern matching", Justification = "<Pending>", Scope = "member", Target = "~M:Wpf.Ui.Violeta.Controls.Compat.ViewManager.UpdateFocusedElement")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0019:Use pattern matching", Justification = "<Pending>", Scope = "member", Target = "~M:Wpf.Ui.Violeta.Controls.Compat.ViewportManagerDownLevel.EnsureScrollers")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0028:Simplify collection initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Wpf.Ui.Violeta.Controls.Compat.RecyclePool.PutElementCore(System.Windows.UIElement,System.String,System.Windows.UIElement)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:Wpf.Ui.Violeta.Controls.Compat.ElementAnimator.OnBoundsChangeAnimationCompleted(System.Windows.UIElement)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:Wpf.Ui.Violeta.Controls.Compat.ElementAnimator.OnHideAnimationCompleted(System.Windows.UIElement)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:Wpf.Ui.Violeta.Controls.Compat.ElementAnimator.OnShowAnimationCompleted(System.Windows.UIElement)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:Wpf.Ui.Violeta.Controls.Compat.ViewportManagerDownLevel.GetLayoutId~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0052:Remove unread private members", Justification = "<Pending>", Scope = "member", Target = "~F:Wpf.Ui.Violeta.Controls.Compat.ItemsRepeater.m_animator")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0052:Remove unread private members", Justification = "<Pending>", Scope = "member", Target = "~F:Wpf.Ui.Violeta.Controls.Compat.ItemsRepeater.m_itemTemplate")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0052:Remove unread private members", Justification = "<Pending>", Scope = "member", Target = "~F:Wpf.Ui.Violeta.Controls.Compat.ItemsRepeater.m_lastAvailableSize")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0052:Remove unread private members", Justification = "<Pending>", Scope = "member", Target = "~F:Wpf.Ui.Violeta.Controls.Compat.ItemsRepeater.m_layout")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0052:Remove unread private members", Justification = "<Pending>", Scope = "member", Target = "~F:Wpf.Ui.Violeta.Controls.Compat.ViewportManagerDownLevel.m_isAnchorOutsideRealizedRange")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:Wpf.Ui.Violeta.Controls.Compat.FlowLayoutAlgorithm.GetAnchorIndex(System.Windows.Size,System.Boolean,System.Double,System.String)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:Wpf.Ui.Violeta.Controls.Compat.FlowLayoutAlgorithm.Generate(Wpf.Ui.Violeta.Controls.Compat.FlowLayoutAlgorithm.GenerateDirection,System.Int32,System.Windows.Size,System.Double,System.Double,System.UInt32,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:Wpf.Ui.Violeta.Controls.Compat.FlowLayoutAlgorithm.ArrangeVirtualizingLayout(System.Windows.Size,Wpf.Ui.Violeta.Controls.Compat.FlowLayoutAlgorithm.LineAlignment,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:Wpf.Ui.Violeta.Controls.Compat.ItemsRepeaterScrollHost.Microsoft#Window#Controls#IRepeaterScrollingSurface#RegisterAnchorCandidate(System.Windows.UIElement)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Wpf.Ui.Violeta.Controls.Compat.ElementManager.EnsureElementRealized(System.Boolean,System.Int32,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Wpf.Ui.Violeta.Controls.Compat.FlowLayoutAlgorithm.Arrange(System.Windows.Size,Wpf.Ui.Violeta.Controls.Compat.VirtualizingLayoutContext,Wpf.Ui.Violeta.Controls.Compat.FlowLayoutAlgorithm.LineAlignment,System.String)~System.Windows.Size")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Wpf.Ui.Violeta.Controls.Compat.FlowLayoutAlgorithm.EstimateExtent(System.Windows.Size,System.String)~System.Windows.Rect")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Wpf.Ui.Violeta.Controls.Compat.FlowLayoutAlgorithm.Measure(System.Windows.Size,Wpf.Ui.Violeta.Controls.Compat.VirtualizingLayoutContext,System.Boolean,System.Double,System.Double,System.UInt32,Wpf.Ui.Violeta.Controls.Compat.ScrollOrientation,System.String)~System.Windows.Size")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Wpf.Ui.Violeta.Controls.Compat.FlowLayoutAlgorithm.OnItemsSourceChanged(System.Object,System.Collections.Specialized.NotifyCollectionChangedEventArgs,Wpf.Ui.Violeta.Controls.Compat.VirtualizingLayoutContext)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Wpf.Ui.Violeta.Controls.Compat.FlowLayoutAlgorithm.PerformLineAlignment(System.Int32,System.Int32,System.Double,System.Double,System.Double,Wpf.Ui.Violeta.Controls.Compat.FlowLayoutAlgorithm.LineAlignment,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Wpf.Ui.Violeta.Controls.Compat.ItemsRepeater.OnAnimatorChanged(Wpf.Ui.Violeta.Controls.Compat.ElementAnimator,Wpf.Ui.Violeta.Controls.Compat.ElementAnimator)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Wpf.Ui.Violeta.Controls.Compat.ItemsSourceView.#ctor(System.Object)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Wpf.Ui.Violeta.Controls.Compat.ScrollViewerExtensions.ChangeView(System.Windows.Controls.ScrollViewer,System.Nullable{System.Double},System.Nullable{System.Double},System.Nullable{System.Single},System.Boolean)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Wpf.Ui.Violeta.Controls.Compat.StackLayout.GetExtent(System.Windows.Size,Wpf.Ui.Violeta.Controls.Compat.VirtualizingLayoutContext,System.Windows.UIElement,System.Int32,System.Windows.Rect,System.Windows.UIElement,System.Int32,System.Windows.Rect)~System.Windows.Rect")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Wpf.Ui.Violeta.Controls.Compat.StackLayout.OnElementMeasured(System.Windows.UIElement,System.Int32,System.Windows.Size,System.Windows.Size,System.Windows.Size,System.Windows.Size,Wpf.Ui.Violeta.Controls.Compat.VirtualizingLayoutContext)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Wpf.Ui.Violeta.Controls.Compat.ViewManager.m_ElementFactoryGetArgs")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Wpf.Ui.Violeta.Controls.Compat.ViewManager.m_ElementFactoryRecycleArgs")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Wpf.Ui.Violeta.Controls.Compat.ItemsRepeater._loadedCounter")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~F:Wpf.Ui.Violeta.Controls.Compat.ItemsRepeater._unloadedCounter")]

