<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWPF>true</UseWPF>
        <LangVersion>preview</LangVersion>
        <AssemblyTitle>Wpf.Ui.Violeta Gallery</AssemblyTitle>
        <AssemblyVersion>4.3.0.11</AssemblyVersion>
        <ApplicationIcon>Resources\Images\wpfui.ico</ApplicationIcon>
        <NoWarn>$(NoWarn);CS2002</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Wpf.Ui.Violeta\Wpf.Ui.Violeta.csproj" />
        <ProjectReference Include="..\Wpf.Ui.Emoji\Wpf.Ui.Emoji.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
        <PackageReference Include="FluentUI.HarmonyOS.Assets" Version="1.0.0" />
        <PackageReference Include="LiteObservableLanguages" Version="1.0.2" />
        <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4129.50" />
        <PackageReference Include="MakeKits.Tools" Version="0.0.20" />
    </ItemGroup>

    <ItemGroup>
        <Resource Include="Resources\Images\*.ico" />
        <Resource Include="Resources\Images\*.png" />
        <Resource Include="$(NuGetPackageRoot)\FluentUI.HarmonyOS.Assets\1.0.0\assets\HarmonyOS_Sans_SC\HarmonyOS_Sans_SC_Regular.ttf">
            <Link>Resources\Fonts\HarmonyOS_Sans_SC_Regular.ttf</Link>
        </Resource>
    </ItemGroup>

    <ItemGroup>
        <Compile Update="Resources\Localization\SH.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>SH.resx</DependentUpon>
        </Compile>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Update="Resources\Localization\SH.resx">
            <!-- Legacy code, keep it for reference. -->
            <!--
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>SH.Designer.cs</LastGenOutput>
            <StronglyTypedFileName>Resources\Localization\SH.Designer.cs</StronglyTypedFileName>
            <StronglyTypedLanguage>CSharp</StronglyTypedLanguage>
            <StronglyTypedNamespace>Wpf.Ui.Violeta.Gallery.Resources.Localization</StronglyTypedNamespace>
            <StronglyTypedClassName>SH</StronglyTypedClassName>
            <Public>true</Public>
            -->
        </EmbeddedResource>
        <EmbeddedResource Update="Resources\Localization\SH.ja.resx">
            <DependentUpon>SH.resx</DependentUpon>
        </EmbeddedResource>
        <EmbeddedResource Update="Resources\Localization\SH.zh-Hans.resx">
            <DependentUpon>SH.resx</DependentUpon>
        </EmbeddedResource>
        <EmbeddedResource Update="Resources\Localization\SH.zh-Hant.resx">
            <DependentUpon>SH.resx</DependentUpon>
        </EmbeddedResource>
    </ItemGroup>

</Project>
